### PR TITLE
add Victini Worlds 22 WC

### PR DESCRIPTION
**Pull request by santacrab2**

### CODE REVIEW

**Comment by kamronbatman** [comment]
Thank you! Can you name it using the same convention please?

**Comment by santacrab2** [comment]
Adjusted, I hope that's correct. I didn't even think of that.

**Comment by Manu098vm** [comment]
Hey santa, the standard nomenclature we use is `[WCID] [GAMES] - [OTName] [(Shiny)] [SpeciesName].wc8`.
In this case it would be `1644 SWSH - Victory Victini.wc8`.

Thanks for the contribution!

**Comment by santacrab2** [comment]
Thank you for the information! I adjusted accordingly! good to know for the future!

**Pull request merged**
