### PR TITLE
Add Gen7 download regulations

### PR DESCRIPTION
**Pull request by Bl4ckSh4rk**
With this commit I would like to add the PGL downloadable regulations. See here for more info https://projectpokemon.org/home/forums/topic/45145-gen-vii-pgl-download-regulations/

Are you ok with the file names or should they be named after the tournaments? Maybe a readme would be a good idea for these files as well. Let me know what you think about it.

### CODE REVIEW

**Comment by kamronbatman** [comment]
Thanks! We could definitely keep these. Although I am wondering if they have any value outside of their interim use during those tournaments.

Also how difficult would it be to recreate the local tournament regulation files?

**Comment by kamronbatman** [comment]
@Bl4ckSh4rk - Thank you for contributing. When new regulations come out, feel free to contribute.
Also if you have time, getting the cup files would be nice too. I have them in a folder, but they have to be formatted.

**Comment by Bl4ckSh4rk** [comment]
@kamronbatman I should have all or at least most of the cup files as well, it just takes a while to organize them. I will let you know if I am missing any.

**Comment by kamronbatman** [comment]
@Bl4ckSh4rk, I'll go over it when I have time. I'll do a file dedupe by content, and then compare them to the regulation/cup files you contribute.  No big deal on time, it is more of a nice-to-have.

**Comment by Bl4ckSh4rk** [comment]
I'm done with sorting my files. Only the first two SM tournaments Battle of Alola and Alola Friendly are missing for all languages.
```
SM
XXXX  Battle of Alola
XXXX  Alola Friendly
4106  International Challenge February, Masters Division
4107  Kanto x Alola Regional Rumble, Junior Division
4108  Kanto x Alola Regional Rumble, Masters Division
4109  2017 International Challenge April, Junior Division (non-JAP only)
4110  2017 International Challenge April, Masters Division (non-JAP only)
4111  2017 International Challenge May, Junior Division
4112  2017 International Challenge May, Masters Division
4113  tiny tourney, Junior Division
4114  tiny tourney, Masters Division
4115  Weakness Cup, Junior Division
4116  Weakness Cup, Masters Division
4117  2017 No Holds Barred, Junior Division
4118  2017 No Holds Barred, Masters Division
4119  Mega Melee, Junior Division
4120  Mega Melee, Masters Division
5101  Japan Championships 2017, Junior Division (JAP only)
5102  Japan Championships 2017, Senior Division (JAP only)
5103  Japan Championships 2017, Master Division (Schedule A) (JAP only)
5104  Japan Championships 2017, Master Division (Schedule B) (JAP only)
5105  Japan Championships 2017, Master Division (Schedule C) (JAP only)
5106  Japan Championships 2017, Master Division (Schedule D) (JAP only)
5107  Japan Championships 2017, Master Division (Schedule E) (JAP only)


USUM
4121  Johto x Alola, Junior Division
4122  Johto x Alola, Masters Division
4123  2018 International Challenge January, Junior Division
4124  2018 International Challenge January, Masters Division
4125  Ultra Sinnoh Classic, Junior Division
4126  Ultra Sinnoh Classic, Masters Division
4127  2018 International Challenge March, Junior Division
4128  2018 International Challenge March, Masters Division
4129  Ultra Kalos Classic, Junior Division (non-JAP only)
4130  Ultra Kalos Classic, Masters Division (non-JAP only)
4131  Ultra No Holds Barred, Junior Division
4132  Ultra No Holds Barred, Masters Division
4133  2018 International Challenge June, Junior Division
4134  2018 International Challenge June, Masters Division
4135  Let's Go! Cup
5109  3rd Pokemon Dragon Cup Preliminaries, Junior Division (JAP only)
5110  3rd Pokemon Dragon Cup Preliminaries, Senior Division (JAP only)
5111  3rd Pokemon Dragon Cup Preliminaries, Master Division (JAP only)
5112  Japan Championships 2018, Junior Division (JAP only)
5113  Japan Championships 2018, Senior Division (JAP only)
5114  Japan Championships 2018, Master Division (JAP only)
```

**Comment by kamronbatman** [comment]
@Bl4ckSh4rk - if someone partook, could they still have those cup files on their 3DS sd card?

**Comment by Bl4ckSh4rk** [comment]
@kamronbatman I found them fortunately.

**Pull request merged**
